### PR TITLE
Precise

### PR DESCRIPTION
**Pull request by nastasi-oq**
First version running on Ubuntu 12.04 (LTS).

CHANGES
- Removed drop and recreation of the DB (we keep "geonode" database)
- Break back-compatibility with 11.04 and older.
- South is directly installed by geonode by pip
- Templates are changed.

Obviously to test it you need a fresh Ubuntu 12.04 (LTS) installation.

### CODE REVIEW

**Comment by bwyss** [comment]
In the Faulted Earth tool the fault source generation failed.
Also, the iframe of the platform should expand to fit the browser hight and width.

**Comment by nastasi-oq** [comment]
Missed regression inherited from site-obs fixed and dimension constraint on gem.faultsource geom field recovered.
Try again, please.

**Comment by bwyss** [comment]
LGTM

**Comment by nastasi-oq** [comment]
From this version only Ubuntu 12.04 LTS is supported.

**Pull request merged**
